jenkins:
  authorizationStrategy: unsecured
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  mode: NORMAL
  numExecutors: 2
  scmCheckoutRetryCount: 2
  systemMessage: |
    Jenkins Docker image built from https://github.com/dmolesUC3/mrt-jenkins-docker

security:
  remotingCLI:
    enabled: false

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git
  jdk:
    installations:
      - name: jdk8
        home: /opt/jdk/jdk8
      - name: jdk11
        home: /opt/jdk/jdk11
  maven:
    installations:
      - name: maven
        home: /usr/share/maven

jobs:
  - script: >
      pipelineJob('mrt-core2') {
        definition {
          cpsScm {
            scm {
              git('http://github.com/dmolesUC3/mrt-core2.git')
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }