jenkins:
  authorizationStrategy: unsecured
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  mode: NORMAL
  numExecutors: 2
  scmCheckoutRetryCount: 2
  systemMessage: |
    Jenkins Docker image built from https://github.com/dmolesUC3/mrt-jenkins-docker

security:
  remotingCLI:
    enabled: false

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git
  jdk:
    installations:
      - name: jdk8
        home: /opt/jdk/jdk8
      - name: jdk11
        home: /opt/jdk/jdk11
  maven:
    installations:
      - name: maven
        home: /usr/share/maven

jobs:
  - script: >
      pipelineJob('mrt-core2-jdk8') {
        parameters {
          stringParam('JDK', 'jdk8')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://github.com/dmolesUC3/mrt-core2.git')
                }
                branch('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }
  - script: >
      pipelineJob('mrt-core2-jdk11') {
        parameters {
          stringParam('JDK', 'jdk11')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://github.com/dmolesUC3/mrt-core2.git')
                }
                branch('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }
